### ISSUE TITLE
BUG crx File unzip

### ISSUE THREAD

**Issue by shedowe19** [speedyconzales/series-scraper#12]
C:\Users\Shedowe\Downloads\Compressed\series-scraper-main_2\series-scraper-main>run.bat
INFO - 2024-04-30 20:16:01,101 - main.py -> ------------- Series-Scraper started ------------
INFO - 2024-04-30 20:16:01,264 - main.py -> Season 1 has 47 Episodes.
Traceback (most recent call last):
  File "C:\Users\Shedowe\Downloads\Compressed\series-scraper-main_2\series-scraper-main\main.py", line 47, in check_episodes
    episode_link = get_episode_link(url, language, provider, season, episode, burning_series)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shedowe\Downloads\Compressed\series-scraper-main_2\series-scraper-main\src\html_scraper.py", line 39, in get_episode_link
    link_to_episode = find_bs_link_to_episode(link_to_episode, provider)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shedowe\Downloads\Compressed\series-scraper-main_2\series-scraper-main\src\html_scraper.py", line 108, in find_bs_link_to_episode
    with SB(uc=True, headless2=True, extension_dir=find_and_unzip_crx()) as sb:
                                                   ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shedowe\Downloads\Compressed\series-scraper-main_2\series-scraper-main\src\html_scraper.py", line 100, in find_and_unzip_crx
    with zipfile.ZipFile(crx_file_path, 'r') as zip_ref:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shedowe\AppData\Local\Programs\Python\Python312\Lib\zipfile\__init__.py", line 1349, in __init__
    self._RealGetContents()
  File "C:\Users\Shedowe\AppData\Local\Programs\Python\Python312\Lib\zipfile\__init__.py", line 1416, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Shedowe\Downloads\Compressed\series-scraper-main_2\series-scraper-main\main.py", line 127, in <module>
    main()
  File "C:\Users\Shedowe\Downloads\Compressed\series-scraper-main_2\series-scraper-main\main.py", line 100, in main
    pending_episodes, language_episodes, future_list = check_episodes(
                                                       ^^^^^^^^^^^^^^^
  File "C:\Users\Shedowe\Downloads\Compressed\series-scraper-main_2\series-scraper-main\main.py", line 54, in check_episodes
    except [HTTPError, URLError] as message:
TypeError: catching classes that do not inherit from BaseException is not allowed

**Comment by shedowe19** [comment]
The CRX File in your Repo could not opened.

This is crx File of the Captcha Solver 

https://cloud.clawsucht.de/index.php/s/AG9HiAjr7wcP8ax

**Comment by shedowe19** [comment]
And then the Script is available ^^

**Comment by shedowe19** [comment]
You can use the Download Link for the Script direct to the crx File: https://cloud.clawsucht.de/index.php/s/AG9HiAjr7wcP8ax/download/recaptcha-solver.crx

**Comment by speedyconzales** [comment]
make sure you did step 5 properly https://github.com/speedyconzales/series-scraper#dependencies
because if the .crx file is present rather than the LFS pointer, then it works just fine

**Comment by speedyconzales** [comment]
That said if you did use git LFS for the first time. You do have to do a `git lfs install` once after install https://docs.github.com/en/repositories/working-with-files/managing-large-files/installing-git-large-file-storage
