### ISSUE TITLE
C:\Projekt Film\series-scraper>python main.py https://bs.to/serie/Final-Space -p Doodstream

### ISSUE THREAD

**Issue by shedowe19** [speedyconzales/series-scraper#39]
```
C:\Projekt Film\series-scraper>python main.py https://bs.to/serie/Final-Space -p Doodstream
INFO - 2024-11-18 14:24:28,742 - main.py -> ------------- Series-Scraper started ------------
INFO - 2024-11-18 14:24:29,103 - main.py -> Season 1 has 10 Episodes.
Traceback (most recent call last):
  File "C:\Projekt Film\series-scraper\main.py", line 129, in <module>
    main()
  File "C:\Projekt Film\series-scraper\main.py", line 101, in main
    provider_episodes, language_episodes, future_list = check_episodes(
                                                        ^^^^^^^^^^^^^^^
  File "C:\Projekt Film\series-scraper\main.py", line 42, in check_episodes
    file_name = f"{season_path}/{content_name} - S{season:02}E{episode:0{3 if len(episodes) > 99 else 2}} - {episode_title}.mp4"
                                                                                                             ^^^^^^^^^^^^^
NameError: name 'episode_title' is not defined

C:\Projekt Film\series-scraper>run.bat

C:\Projekt Film\series-scraper>python main.py https://bs.to/serie/Final-Space -p Doodstream
INFO - 2024-11-18 15:19:20,052 - main.py -> ------------- Series-Scraper started ------------
INFO - 2024-11-18 15:19:20,357 - main.py -> Season 1 has 10 Episodes.

Warning: uc_driver update needed. Getting it now:

*** chromedriver to download = 130.0.6723.116 (Previous Version)

Downloading chromedriver-win64.zip from:
https://storage.googleapis.com/chrome-for-testing-public/130.0.6723.116/win64/chromedriver-win64.zip ...
Download Complete!

Extracting ['chromedriver.exe'] from chromedriver-win64.zip ...
Unzip Complete!

The file [uc_driver.exe] was saved to:
C:\Users\Shedowe\AppData\Roaming\Python\Python312\site-packages\seleniumbase\drivers\uc_driver.exe

Making [uc_driver.exe 130.0.6723.116] executable ...
[uc_driver.exe 130.0.6723.116] is now ready for use!


*** chromedriver to download = 130.0.6723.116 (Previous Version)

Downloading chromedriver-win64.zip from:
https://storage.googleapis.com/chrome-for-testing-public/130.0.6723.116/win64/chromedriver-win64.zip ...
Download Complete!

Extracting ['chromedriver.exe'] from chromedriver-win64.zip ...
Unzip Complete!

The file [chromedriver.exe] was saved to:
C:\Users\Shedowe\AppData\Roaming\Python\Python312\site-packages\seleniumbase\drivers\chromedriver.exe

Making [chromedriver.exe 130.0.6723.116] executable ...
[chromedriver.exe 130.0.6723.116] is now ready for use!


DevTools listening on ws://127.0.0.1:25265/devtools/browser/e1531236-7343-4188-86f7-55af644d1902
ERROR - 2024-11-18 15:19:43,163 - main.py -> <urlopen error [Errno 11001] getaddrinfo failed> while working on episode 1 and provider Doodstream
Traceback (most recent call last):
  File "C:\Projekt Film\series-scraper\main.py", line 129, in <module>
    main()
  File "C:\Projekt Film\series-scraper\main.py", line 101, in main
    provider_episodes, language_episodes, future_list = check_episodes(
                                                        ^^^^^^^^^^^^^^^
  File "C:\Projekt Film\series-scraper\main.py", line 47, in check_episodes
    episode_link = get_episode_link(url, language, provider, season, episode, burning_series)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projekt Film\series-scraper\src\html_scraper.py", line 43, in get_episode_link
    link_to_episode = find_bs_link_to_episode(link_to_episode, provider)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projekt Film\series-scraper\src\html_scraper.py", line 141, in find_bs_link_to_episode
    sb.click('.cc-compliance a')
  File "C:\Users\Shedowe\AppData\Roaming\Python\Python312\site-packages\seleniumbase\fixtures\base_case.py", line 413, in click
    element = page_actions.wait_for_element_visible(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Shedowe\AppData\Roaming\Python\Python312\site-packages\seleniumbase\fixtures\page_actions.py", line 496, in wait_for_element_visible
    timeout_exception(NoSuchElementException, message)
  File "C:\Users\Shedowe\AppData\Roaming\Python\Python312\site-packages\seleniumbase\fixtures\page_actions.py", line 254, in timeout_exception
    raise exc(msg)
seleniumbase.common.exceptions.NoSuchElementException: Message:
 Element {.cc-compliance a} was not present after 7 seconds!

C:\Projekt Film\series-scraper>
```

**Comment by speedyconzales** [comment]
could not reproduce. it is working fine for me
